### ISSUE TITLE
Deleting your token doesn't actually hide it.

### ISSUE THREAD

**Issue by lukekrikorian** [jma8774/DiscordBot#1]
Hey there, just wanted to let you know that the discord token you deleted in [this commit](https://github.com/jma8774/DiscordBot/commit/3d0cd1b9e9c1a837a7531c55bf71f04845dd78c8) isn't actually hidden, due to the way github and commits work. You pretty much have a few options if you want to keep it hidden. You can delete the repo and copy the code to a new one (without the token of course) or you can follow the instructions [here](https://help.github.com/articles/removing-sensitive-data-from-a-repository/).

It's a pretty easy mistake to make, I've done it a few times myself :) 

Good luck with this project! :)

**Comment by jma8774** [comment]
Hi,

Thanks for letting me know. Unfortunately, I had to learn it the hard way.
After the bot got hacked, we changed the token and made sure that we don't
commit it ever again.

I appreciate you for letting us know. :D

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
